version: 2
mergeable:
  - when: issue_comment.*
    name: "Check if Atlantis wants to destroy resources"
    filter:
      - do: author
        must_include:
          regex: "calexandre"
          message: "some message related to author filter"
    validate:
      - do: comment
        must_exclude:
          regex:
            - "Plan: [0-9]+ to add, [0-9]+ to change, [1-9]+ to destroy\\."
          message: |
            "You terraform plan is going to destroy resources. You'll need an extra approval."
    pass:
      - do: comment
        payload:
          body: "you passed"
        leave_old_comment: false
    fail: # list of actions to be executed when at least one validation fails. Specify one or more. Omit this tag if no actions are needed.
      - do: comment
        payload:
          body: "you failed"
        leave_old_comment: false
    error: # list of actions to be executed when at least one validator throws an error. Specify one or more. Omit this tag if no actions are needed.
      - do: comment
        payload:
          body: "you errored"
        leave_old_comment: false
        
