version: 2
mergeable:
  - when: issue_comment.*
    name: "Check if Atlantis wants to destroy resources"
    filter:
      - do: author
        must_include:
          regex: "calexandre"
          message: "some message related to author filter"
    validate:
      - do: comment
        must_include:
          regex: 'test'
          message: "comment must_include message"
    pass:
      - do: comment
        payload:
          body: "you passed"
        leave_old_comment: false
    fail: # list of actions to be executed when at least one validation fails. Specify one or more. Omit this tag if no actions are needed.
      - do: comment
        payload:
          body: "you failed"
        leave_old_comment: false
    error: # list of actions to be executed when at least one validator throws an error. Specify one or more. Omit this tag if no actions are needed.
      - do: comment
        payload:
          body: "you errored"
        leave_old_comment: false
        
